### ISSUE TITLE
Hi Expo at it again to v37.0.0

### ISSUE THREAD

**Issue by branx86** [rdagger/Expo-Solar-Tracker#7]
Expo has upgraded again out of the scope from 35 to 37.0.0. Can i send you some money paypal, cashapp as I hate to keep bothering you over this, but I love your software.

**Comment by rdagger** [comment]
Thanks for the offer.  I upgraded the project to Expo 40.  Please let me know if there are any issues because it required a major rewrite and I don’t have time to thoroughly test it.  One reason I don’t use Expo any more is because addressing all the breaking changes between versions is too cumbersome.
